config/routes.rb
Rails.application.routes.draw do
  resources :daily_updates
  get 'pages/home'
  get 'pages/other'

  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_update.rb
class DailyUpdate < ApplicationRecord
  has_rich_text :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_updates_controller.rb
class DailyUpdatesController < ApplicationController
  before_action :set_daily_update, only: [:show, :edit, :update, :destroy]

  # GET /daily_updates
  # GET /daily_updates.json
  def index
    @daily_updates = DailyUpdate.all
  end

  # GET /daily_updates/1
  # GET /daily_updates/1.json
  def show
  end

  # GET /daily_updates/new
  def new
    @daily_update = DailyUpdate.new
  end

  # GET /daily_updates/1/edit
  def edit
  end

  # POST /daily_updates
  # POST /daily_updates.json
  def create
    @daily_update = DailyUpdate.new(daily_update_params)

    respond_to do |format|
      if @daily_update.save
        format.html { redirect_to @daily_update, notice: 'Daily update was successfully created.' }
        format.json { render :show, status: :created, location: @daily_update }
      else
        format.html { render :new }
        format.json { render json: @daily_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_updates/1
  # PATCH/PUT /daily_updates/1.json
  def update
    respond_to do |format|
      if @daily_update.update(daily_update_params)
        format.html { redirect_to @daily_update, notice: 'Daily update was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_update }
      else
        format.html { render :edit }
        format.json { render json: @daily_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_updates/1
  # DELETE /daily_updates/1.json
  def destroy
    @daily_update.destroy
    respond_to do |format|
      format.html { redirect_to daily_updates_url, notice: 'Daily update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_update
      @daily_update = DailyUpdate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def daily_update_params
      params.require(:daily_update).permit(:date, :title, :body, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_updates_helper.rb
module DailyUpdatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/daily_updates/_form.html.erb
<%= form_with(model: daily_update, local: true) do |form| %>
  <% if daily_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily_update.errors.count, "error") %> prohibited this daily_update from being saved:</h2>

      <ul>
        <% daily_update.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_updates/edit.html.erb
<h1>Editing Daily Update</h1>

<%= render 'form', daily_update: @daily_update %>

<%= link_to 'Show', @daily_update %> |
<%= link_to 'Back', daily_updates_path %>

app/views/daily_updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily Updates</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_updates.each do |daily_update| %>
      <tr>
        <td><%= daily_update.date %></td>
        <td><%= daily_update.title %></td>
        <td><%= daily_update.body %></td>
        <td><%= link_to 'Show', daily_update %></td>
        <td><%= link_to 'Edit', edit_daily_update_path(daily_update) %></td>
        <td><%= link_to 'Destroy', daily_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Update', new_daily_update_path %>

app/views/daily_updates/new.html.erb
<h1>New Daily Update</h1>

<%= render 'form', daily_update: @daily_update %>

<%= link_to 'Back', daily_updates_path %>

app/views/daily_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @daily_update.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @daily_update.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @daily_update.body %>
</p>

<%= link_to 'Edit', edit_daily_update_path(@daily_update) %> |
<%= link_to 'Back', daily_updates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Just Dil</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Just Dil", root_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hero">
	
</div>

<table>
	<tr>
		<td id="home-body">
			<div class="post">
				<h1>This is an H1 Headline!</h1>
				<h2>An h2 subtitle here.</h2>
				<h3>and of course ... h3</h3>
				<p>With a paragraph to boot.</p>
				<p>One of the more pernicious mistruths surrounding the debate about TikTok is that this will potentially lead to the splintering of the Internet; this completely erases the history of China’s Great Firewall, started 23 years ago, which effectively cut China off from most Western services. That the U.S. may finally respond in kind is a reflection of reality, not the creation of a new one.</p>
				<p>What is new is the increased splintering in the non-China Internet: the U.S. model is still the default for most of the world, but the European Union and India are increasingly pursuing their own paths.</p>
			</div>
			<div class="post">
				<h1>This is an H1 Headline!</h1>
				<h2>An h2 subtitle here.</h2>
				<h3>and of course ... h3</h3>
				<p>With a paragraph to boot.</p>
				<p>One of the more pernicious mistruths surrounding the debate about TikTok is that this will potentially lead to the splintering of the Internet; this completely erases the history of China’s Great Firewall, started 23 years ago, which effectively cut China off from most Western services. That the U.S. may finally respond in kind is a reflection of reality, not the creation of a new one.</p>
				<p>What is new is the increased splintering in the non-China Internet: the U.S. model is still the default for most of the world, but the European Union and India are increasingly pursuing their own paths.</p>
			</div>
			<div class="post">
				<h1>This is an H1 Headline!</h1>
				<h2>An h2 subtitle here.</h2>
				<h3>and of course ... h3</h3>
				<p>With a paragraph to boot.</p>
				<p>One of the more pernicious mistruths surrounding the debate about TikTok is that this will potentially lead to the splintering of the Internet; this completely erases the history of China’s Great Firewall, started 23 years ago, which effectively cut China off from most Western services. That the U.S. may finally respond in kind is a reflection of reality, not the creation of a new one.</p>
				<p>What is new is the increased splintering in the non-China Internet: the U.S. model is still the default for most of the world, but the European Union and India are increasingly pursuing their own paths.</p>
			</div>
		</td>
		<td id="home-sidebar">
						
		</td>
	</tr>
</table>

app/views/pages/other.html.erb
<h1>Pages#other</h1>
<p>Find me in app/views/pages/other.html.erb</p>